name: my_diet
description: "A new Flutter project."
publish_to: 'none' # Захист від випадкової публікації проєкту на pub.dev

version: 1.0.0+1

# Сумісна версія Dart SDK
environment:
  sdk: ^3.12.0

# ОСНОВНІ ЗАЛЕЖНОСТІ (Пакетні бібліотеки, які працюють у додатку)
dependencies:
  flutter:
    sdk: flutter

  # Форматування дат, часу та робота з українською локалізацією ('uk_UA')
  intl: ^0.19.0

  # УНІВЕРСАЛЬНЕ СХОВИЩЕ: Працює і в Chrome (LocalStorage), і у Windows, і на мобільних
  shared_preferences: ^2.2.2

  # Іконки в стилі iOS (Cupertino)
  cupertino_icons: ^1.0.8

# ЗАЛЕЖНОСТІ ДЛЯ РОЗРОБКИ (Використовуються лише під час написання коду та тестування)
dev_dependencies:
  # Бібліотека для автоматичних тестів
  flutter_test:
    sdk: flutter

  # Стандартний аналізатор якості та правил коду Flutter
  flutter_lints: ^6.0.0

# СПЕЦІАЛЬНІ НАЛАШТУВАННЯ FLUTTER
flutter:
  # Вмикаємо системні іконки Material Design
  uses-material-design: true

  # Список ресурсів, які запаковуються всередину додатка
  assets:
    - assets/products_database.json