@echo off
echo Stopping Gradle...
call android\gradlew --stop
echo Cleaning Flutter...
call flutter clean
echo Getting Packages...
call flutter pub get
echo Cleaning Android Build...
cd android
call gradlew clean
cd ..
echo Running App...
call flutter run -d RZCW1024D4H
pause